create table if not exists government_qna_items (
    id bigint not null auto_increment,
    external_id bigint null,
    source_name varchar(255) not null,
    source_url varchar(1500) not null,
    source_url_hash char(64) not null,
    detail_url varchar(1500),
    original_url varchar(1500),
    title varchar(1500) not null,
    question_text mediumtext,
    answer_text longtext,
    answer_html longtext,
    summary_text mediumtext,
    responding_authority varchar(500),
    category_name varchar(500),
    tags varchar(1000),
    published_date date,
    source_payload_json longtext,
    content_hash varchar(64),
    citation_status varchar(32) not null default 'UNRESOLVED',
    citation_count int not null default 0,
    matched_citation_count int not null default 0,
    missing_citation_count int not null default 0,
    crawled_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    primary key (id),
    unique key uk_government_qna_source_url_hash (source_url_hash),
    index idx_government_qna_source (source_name),
    index idx_government_qna_published_at (published_date),
    index idx_government_qna_item_citation_status (citation_status)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists government_qna_citations (
    id bigint not null auto_increment,
    qna_item_id bigint not null,
    citation_hash char(64) not null,
    raw_text varchar(1500) not null,
    document_number varchar(255),
    document_title varchar(1000),
    article_refs varchar(1000),
    matched_document_id bigint,
    matched_document_title varchar(1500),
    matched_document_number varchar(255),
    matched_document_source varchar(2048),
    match_status varchar(32) not null,
    match_reason varchar(500),
    created_at timestamp not null default current_timestamp,
    primary key (id),
    unique key uk_government_qna_citation_hash (qna_item_id, citation_hash),
    index idx_government_qna_citation_document (matched_document_id),
    index idx_government_qna_citation_status (match_status),
    index idx_government_qna_citation_number (document_number),
    constraint fk_government_qna_citations_item
        foreign key (qna_item_id) references government_qna_items(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
