package com.lawassistant.lawservice.importer;

import static org.assertj.core.api.Assertions.assertThat;

import com.lawassistant.lawservice.embedding.EmbeddingEventPublisher;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericRecord;
import org.apache.parquet.avro.AvroParquetWriter;
import org.apache.parquet.hadoop.metadata.CompressionCodecName;
import org.apache.parquet.io.LocalOutputFile;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.cache.CacheManager;
import org.springframework.cache.concurrent.ConcurrentMapCacheManager;
import org.springframework.jdbc.core.JdbcTemplate;

class ProvidedDataImportServiceTests {
    @TempDir
    private Path tempDir;

    private JdbcTemplate jdbcTemplate;
    private RecordingPublisher publisher;
    private CacheManager cacheManager;
    private ProvidedDataImportService importService;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + UUID.randomUUID()
                + ";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table legal_documents (
                    id bigint not null primary key,
                    external_source varchar(255),
                    external_docid varchar(255),
                    title varchar(1500) not null,
                    document_number varchar(255),
                    issued_date date,
                    document_type varchar(255),
                    effective_date date,
                    expired_date date,
                    source varchar(2048),
                    source_url varchar(2048),
                    gazette_date_raw varchar(255),
                    sector varchar(255),
                    field varchar(1000),
                    issuing_authority varchar(500),
                    signer_title varchar(255),
                    signer_name varchar(255),
                    scope varchar(500),
                    application_info double,
                    validity_status varchar(255),
                    embedding_status varchar(32) not null default 'PENDING',
                    indexed_at timestamp(6) null,
                    created_at timestamp(6) not null default current_timestamp(6),
                    updated_at timestamp(6) not null default current_timestamp(6)
                )
                """);
        jdbcTemplate.execute("""
                create table legal_document_contents (
                    document_id bigint not null primary key,
                    content_html clob not null,
                    content_text clob,
                    created_at timestamp(6) not null default current_timestamp(6),
                    updated_at timestamp(6) not null default current_timestamp(6)
                )
                """);
        jdbcTemplate.execute("""
                create table legal_document_relationships (
                    id bigint generated by default as identity primary key,
                    document_id bigint not null,
                    related_document_id bigint not null,
                    relationship_type varchar(255) not null,
                    unique(document_id, related_document_id, relationship_type)
                )
                """);
        publisher = new RecordingPublisher(jdbcTemplate);
        cacheManager = new ConcurrentMapCacheManager("legal-document-detail");
        importService = new ProvidedDataImportService(jdbcTemplate, publisher, cacheManager);
    }

    @Test
    void importPublishesEventsOnlyAfterContentAndRelationshipsAreVisible() throws Exception {
        writeMetadata(42L, "Luật thử nghiệm");
        writeContentWithId("content.parquet", 42L, "Điều 1. Nội dung");
        writeRelationships(42L, 100L);
        cacheManager.getCache("legal-document-detail").put(42L, "stale");

        ProvidedDataImportResult result = importService.importFrom(tempDir, true);

        assertThat(result.metadataRows()).isEqualTo(1);
        assertThat(result.contentRows()).isEqualTo(1);
        assertThat(result.relationshipRows()).isEqualTo(1);
        assertThat(publisher.publishedIds).containsExactly(42L);
        assertThat(publisher.visibleContentRowsAtPublish).containsExactly(1);
        assertThat(publisher.visibleRelationshipRowsAtPublish).containsExactly(1);
        assertThat(cacheManager.getCache("legal-document-detail").get(42L)).isNull();
    }

    @Test
    void importContentAcceptsLegacyIdSchema() throws Exception {
        writeMetadata(43L, "Luật content id");
        writeContentWithId("content.parquet", 43L, "Nội dung từ id");
        writeRelationships(43L, 101L);

        importService.importFrom(tempDir, false);

        String content = jdbcTemplate.queryForObject(
                "select content_text from legal_document_contents where document_id = 43",
                String.class);
        assertThat(content).isEqualTo("Nội dung từ id");
    }

    @Test
    void importRelationshipsReplacesSnapshotAndRemovesStaleEdges() throws Exception {
        writeMetadata(44L, "Luật quan hệ");
        writeContentWithId("content.parquet", 44L, "Nội dung");
        writeRelationships(44L, 101L);
        importService.importFrom(tempDir, false);

        writeRelationships(44L, 102L);
        importService.importFrom(tempDir, false);

        List<Long> relatedIds = jdbcTemplate.queryForList(
                "select related_document_id from legal_document_relationships where document_id = 44",
                Long.class);
        assertThat(relatedIds).containsExactly(102L);
    }

    private void writeMetadata(Long id, String title) throws IOException {
        Schema schema = SchemaBuilder.record("metadata").fields()
                .requiredLong("id")
                .requiredString("title")
                .optionalString("document_number")
                .optionalString("loai_van_ban")
                .optionalString("tinh_trang_hieu_luc")
                .endRecord();
        GenericRecord record = new GenericData.Record(schema);
        record.put("id", id);
        record.put("title", title);
        record.put("document_number", "01/2026/QH");
        record.put("loai_van_ban", "Luật");
        record.put("tinh_trang_hieu_luc", "Còn hiệu lực");
        writeParquet(tempDir.resolve("metadata.parquet"), schema, List.of(record));
    }

    private void writeContentWithId(String filename, Long id, String text) throws IOException {
        Schema schema = SchemaBuilder.record("content").fields()
                .requiredLong("id")
                .optionalString("content_text")
                .optionalString("content_html")
                .endRecord();
        GenericRecord record = new GenericData.Record(schema);
        record.put("id", id);
        record.put("content_text", text);
        record.put("content_html", "<p>" + text + "</p>");
        writeParquet(tempDir.resolve(filename), schema, List.of(record));
    }

    private void writeRelationships(Long documentId, Long relatedDocumentId) throws IOException {
        Schema schema = SchemaBuilder.record("relationships").fields()
                .requiredLong("document_id")
                .requiredLong("related_document_id")
                .requiredString("relationship_type")
                .endRecord();
        GenericRecord record = new GenericData.Record(schema);
        record.put("document_id", documentId);
        record.put("related_document_id", relatedDocumentId);
        record.put("relationship_type", "amends");
        writeParquet(tempDir.resolve("relationships.parquet"), schema, List.of(record));
    }

    private static void writeParquet(
            Path path,
            Schema schema,
            List<GenericRecord> records) throws IOException {
        Files.deleteIfExists(path);
        try (var writer = AvroParquetWriter.<GenericRecord>builder(new LocalOutputFile(path))
                .withSchema(schema)
                .withCompressionCodec(CompressionCodecName.UNCOMPRESSED)
                .build()) {
            for (GenericRecord record : records) {
                writer.write(record);
            }
        }
    }

    private static final class RecordingPublisher extends EmbeddingEventPublisher {
        private final JdbcTemplate jdbcTemplate;
        private final List<Long> publishedIds = new ArrayList<>();
        private final List<Integer> visibleContentRowsAtPublish = new ArrayList<>();
        private final List<Integer> visibleRelationshipRowsAtPublish = new ArrayList<>();

        private RecordingPublisher(JdbcTemplate jdbcTemplate) {
            super(null, null);
            this.jdbcTemplate = jdbcTemplate;
        }

        @Override
        public void publishDocumentUpdated(Long documentId) {
            publishedIds.add(documentId);
            visibleContentRowsAtPublish.add(jdbcTemplate.queryForObject(
                    "select count(*) from legal_document_contents where document_id = ?",
                    Integer.class,
                    documentId));
            visibleRelationshipRowsAtPublish.add(jdbcTemplate.queryForObject(
                    "select count(*) from legal_document_relationships where document_id = ?",
                    Integer.class,
                    documentId));
        }
    }
}
