services:
  qdrant:
    image: qdrant/qdrant:v1.12.6
    ports:
      - "6333:6333"
      - "6334:6334"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data:
